# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_filename', models.URLField(blank=True, null=True)),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('formula', models.CharField(blank=True, max_length=255, null=True)),
                ('strunz_classification', models.CharField(blank=True, max_length=255, null=True)),
                ('crystal_system', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_cell', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('crystal_symmetry', models.CharField(blank=True, max_length=255, null=True)),
                ('cleavage', models.CharField(blank=True, max_length=255, null=True)),
                ('mohs_scale_hardness', models.CharField(blank=True, max_length=255, null=True)),
                ('luster', models.CharField(blank=True, max_length=255, null=True)),
                ('streak', models.CharField(blank=True, max_length=255, null=True)),
                ('diaphaneity', models.CharField(blank=True, max_length=255, null=True)),
                ('optical_properties', models.CharField(blank=True, max_length=255, null=True)),
                ('refractive_index', models.CharField(blank=True, max_length=255, null=True)),
                ('crystal_habit', models.CharField(blank=True, max_length=255, null=True)),
                ('specific_gravity', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
