#!/bin/bash
mv -v images/200px-Adamsite-%28Y%29-167345.jpg images/200px-Adamsite-\(Y\)-167345.jpg
mv -v images/200px-Hectorite_Hydrous_magnesium_iron_silicate_Hector%2C_California.jpg images/200px-Hectorite_Hydrous_magnesium_iron_silicate_Hector,_California.jpg
mv -v images/200px-Loparite-%28Ce%29-41714.jpg images/200px-Loparite-\(Ce\)-41714.jpg
mv -v images/200px-Melanterite2_-_Copperas_Mountain%2C_Paxton_Township%2C_Ross_Co%2C_Ohio%2C_USA.jpg images/200px-Melanterite2_-_Copperas_Mountain,_Paxton_Township,_Ross_Co,_Ohio,_USA.jpg
mv -v images/200px-Rozenit%2C_Maroko.jpg images/200px-Rozenit,_Maroko.jpg
mv -v images/240px-%C3%85kermanite%2C_Calcite%2C_Hillebrandite%2C_Tilleyite_-_Mineralogisches_Museum_Bonn1.jpg images/240px-Åkermanite,_Calcite,_Hillebrandite,_Tilleyite_-_Mineralogisches_Museum_Bonn1.jpg
mv -v images/240px-%C3%89osphorite_sur_quartz_rose_cristallis%C3%A9_5157.jpg images/240px-Éosphorite_sur_quartz_rose_cristallisé_5157.jpg
mv -v images/240px-Abelsonite_-_Green_River_Formation%2C_Uintah_County%2C_Utah%2C_USA.jpg images/240px-Abelsonite_-_Green_River_Formation,_Uintah_County,_Utah,_USA.jpg
mv -v images/240px-Abernathyite%2C_Heinrichite-497484.jpg images/240px-Abernathyite,_Heinrichite-497484.jpg
mv -v images/240px-Abhurite_-_Shipwreck_Hydra%2C_South_coast_of_Norway.jpg images/240px-Abhurite_-_Shipwreck_Hydra,_South_coast_of_Norway.jpg
mv -v images/240px-Acanthite_on_Calcite_-_Freiberg%2C_Erzgebirge%2C_Saxony%2C_Germany.jpg images/240px-Acanthite_on_Calcite_-_Freiberg,_Erzgebirge,_Saxony,_Germany.jpg
mv -v images/240px-Aeschynite-%28Y%29-180743.jpg images/240px-Aeschynite-\(Y\)-180743.jpg
mv -v images/240px-Agardite-%28Ce%29-174233.jpg images/240px-Agardite-\(Ce\)-174233.jpg
mv -v images/240px-Aguilarite_-_San_Carlos_Mine%2C_La_Luz%2C_Guanajuato%2C_Mexico.jpg images/240px-Aguilarite_-_San_Carlos_Mine,_La_Luz,_Guanajuato,_Mexico.jpg
mv -v images/240px-Aikinite_-_Beresowsk%2C_Ural.JPG images/240px-Aikinite_-_Beresowsk,_Ural.JPG
mv -v images/240px-Albite_-_Crete_%28Kriti%29_Island%2C_Greece.jpg images/240px-Albite_-_Crete_\(Kriti\)_Island,_Greece.jpg
mv -v images/240px-Algodonit_-_Houghton_County%2C_Michigan%2C_USA.jpg images/240px-Algodonit_-_Houghton_County,_Michigan,_USA.jpg
mv -v images/240px-Allanite-%28Ce%29_-_Mary_Kathleen_Mine%2C_Mount_Isa%2C_Queensland%2C_Australia.jpg images/240px-Allanite-\(Ce\)_-_Mary_Kathleen_Mine,_Mount_Isa,_Queensland,_Australia.jpg
mv -v images/240px-Aluminite_-_Newhaven%2C_Sussex%2C_England.jpg images/240px-Aluminite_-_Newhaven,_Sussex,_England.jpg
mv -v images/240px-Alunogen_-_Almyras%2C_Agia_Varvara%2C_Cyprus.jpg images/240px-Alunogen_-_Almyras,_Agia_Varvara,_Cyprus.jpg
mv -v images/240px-Amarantite_-_Javir-e-Sagand%2C_Yazd_Province%2C_Iran.jpg images/240px-Amarantite_-_Javir-e-Sagand,_Yazd_Province,_Iran.jpg
mv -v images/240px-Analcime%2C_Aegirine%2C_Natrolite-225835.jpg images/240px-Analcime,_Aegirine,_Natrolite-225835.jpg
mv -v images/240px-Andorite_-_Itos_Mine%2C_Oruro_City%2C_Cercado%2C_Oruro_Department%2C_Bolivia.jpg images/240px-Andorite_-_Itos_Mine,_Oruro_City,_Cercado,_Oruro_Department,_Bolivia.jpg
mv -v images/240px-Angl%C3%A9site-touizit_Monocristal.jpg images/240px-Anglésite-touizit_Monocristal.jpg
mv -v images/240px-Ank%C3%A9rite_Quartz_P%C3%A9rou.jpg images/240px-Ankérite_Quartz_Pérou.jpg
mv -v images/240px-Anthophyllite_Su%C3%A8de_Fond.jpg images/240px-Anthophyllite_Suède_Fond.jpg
mv -v images/240px-Anyolite%2C_pargasite%2C_rubis_3.jpg images/240px-Anyolite,_pargasite,_rubis_3.jpg
mv -v images/240px-Apophyllite-%28KF%29-114628.jpg images/240px-Apophyllite-\(KF\)-114628.jpg
mv -v images/240px-Apophyllite-Kinoite_%280%29_Fond.jpg images/240px-Apophyllite-Kinoite_\(0\)_Fond.jpg
mv -v images/240px-Armalcolite_-_Wat_Lu_Mine%2C_Mogok%2C_Myanmar.jpg images/240px-Armalcolite_-_Wat_Lu_Mine,_Mogok,_Myanmar.jpg
mv -v images/240px-Arsenopyrite%2C_Panasqueira_Mine%2C_Portugal.jpg images/240px-Arsenopyrite,_Panasqueira_Mine,_Portugal.jpg
mv -v images/240px-Asisite_-_Kombat_Mine%2C_Namibia.jpg images/240px-Asisite_-_Kombat_Mine,_Namibia.jpg
mv -v images/240px-B%C3%B6hmite-89904.jpg images/240px-Böhmite-89904.jpg
mv -v images/240px-Biotite_aggregate_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Biotite_aggregate_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Bismutit_%28Wismutcarbonat%29_-_Schneeberg%2C_Erzgebirge.jpg images/240px-Bismutit_\(Wismutcarbonat\)_-_Schneeberg,_Erzgebirge.jpg
mv -v images/240px-Blenda_smolista_%2B_coffinit.jpg images/240px-Blenda_smolista_+_coffinit.jpg
mv -v images/240px-Braunit_-_San_Marcel%2C_Piemont.jpg images/240px-Braunit_-_San_Marcel,_Piemont.jpg
mv -v images/240px-Bromargyrit_mit_gediegen_Silber_-_San_Onofre%2C_Mexiko.jpg images/240px-Bromargyrit_mit_gediegen_Silber_-_San_Onofre,_Mexiko.jpg
mv -v images/240px-Calcite-Apophyllite-%28KF%29-Stilbite-Ca-233193.jpg images/240px-Calcite-Apophyllite-\(KF\)-Stilbite-Ca-233193.jpg
mv -v images/240px-Caledonit_auf_Cerussit_-_Mineralogisches_Museum_Bonn_%287354%29.jpg images/240px-Caledonit_auf_Cerussit_-_Mineralogisches_Museum_Bonn_\(7354\).jpg
mv -v images/240px-Calomel%2C_Terlinguaite-222734.jpg images/240px-Calomel,_Terlinguaite-222734.jpg
mv -v images/240px-Carnotit_auf_fossilisiertem_Holz_-_St-George%2C_Utah.jpg images/240px-Carnotit_auf_fossilisiertem_Holz_-_St-George,_Utah.jpg
mv -v images/240px-Chamosite%2C_Saponite%2C_Copper-188771.jpg images/240px-Chamosite,_Saponite,_Copper-188771.jpg
mv -v images/240px-Clinozoisite%2C_Amphibole_Group_-_Mount_Belvidere_Quarries%2C_Vermont%2C_USA.jpg images/240px-Clinozoisite,_Amphibole_Group_-_Mount_Belvidere_Quarries,_Vermont,_USA.jpg
mv -v images/240px-Coloradoite%2C_Pyrite%2C_Quartz-338840.jpg images/240px-Coloradoite,_Pyrite,_Quartz-338840.jpg
mv -v images/240px-Crocoite_from_the_Dundas_extended_mine%2C_Dundas%2C_Tasmania%2C_Australia.jpg images/240px-Crocoite_from_the_Dundas_extended_mine,_Dundas,_Tasmania,_Australia.jpg
mv -v images/240px-Crossite_with_natrolite_Complex_Silicate_near_the_Dallas_Gem_Mine%2C_San_Benito_County%2C_California_2397.jpg images/240px-Crossite_with_natrolite_Complex_Silicate_near_the_Dallas_Gem_Mine,_San_Benito_County,_California_2397.jpg
mv -v images/240px-Crystals_of_black_riebeckite_in_alkaline_pegmatite%2C_near_%C3%89visa_%28Corsica%2C_France%29.jpg images/240px-Crystals_of_black_riebeckite_in_alkaline_pegmatite,_near_Évisa_\(Corsica,_France\).jpg
mv -v images/240px-Davidite-%28La%29-35242.jpg images/240px-Davidite-\(La\)-35242.jpg
mv -v images/240px-Diadochit_-_Lodenitz%2C_B%C3%B6hmen.jpg images/240px-Diadochit_-_Lodenitz,_Böhmen.jpg
mv -v images/240px-Dolomite-Magn%C3%A9site-_Navarre.jpg images/240px-Dolomite-Magnésite-_Navarre.jpg
mv -v images/240px-Ellestadite-%28F%29-Calcite-215134.jpg images/240px-Ellestadite-\(F\)-Calcite-215134.jpg
mv -v images/240px-Erionit_Na%2C_Dunseverick%2C_Antrim_Co.%2C_Irlandia_Pn..jpg images/240px-Erionit_Na,_Dunseverick,_Antrim_Co.,_Irlandia_Pn..jpg
mv -v images/240px-Euclase_%28Br%C3%A9sil%29.jpg images/240px-Euclase_\(Brésil\).jpg
mv -v images/240px-Euxenite_-_Vegusdal%2C_Norvegia_01.jpg images/240px-Euxenite_-_Vegusdal,_Norvegia_01.jpg
mv -v images/240px-Faujasite-Na_-_Poudrette_quarry%2C_Mont_Saint-Hilaire%2C_Quebec%2C_Canada.jpg images/240px-Faujasite-Na_-_Poudrette_quarry,_Mont_Saint-Hilaire,_Quebec,_Canada.jpg
mv -v images/240px-Fayalite_crystal_group_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Fayalite_crystal_group_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Ferruccite%2C_Avogadrite_-_Vesuvius%2C_Italia.jpg images/240px-Ferruccite,_Avogadrite_-_Vesuvius,_Italia.jpg
mv -v images/240px-Fettelite_-_Chanarcillo%2C_Copiapo_Province%2C_Atacama_Region%2C_Chile.jpg images/240px-Fettelite_-_Chanarcillo,_Copiapo_Province,_Atacama_Region,_Chile.jpg
mv -v images/240px-Fluckite_%28Sainte-Marie-aux-Mines%29-Mus%C3%A9e_de_min%C3%A9ralogie_de_Strasbourg.jpg images/240px-Fluckite_\(Sainte-Marie-aux-Mines\)-Musée_de_minéralogie_de_Strasbourg.jpg
mv -v images/240px-Forsterite_on_Sanidine_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Forsterite_on_Sanidine_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Franklinit_mit_Zinkit_-_Franklin%2C_New_Jersey%2C_USA.jpg images/240px-Franklinit_mit_Zinkit_-_Franklin,_New_Jersey,_USA.jpg
mv -v images/240px-Freieslebenit_-_Mineralogisches_Museum_Bonn_%287267%29.jpg images/240px-Freieslebenit_-_Mineralogisches_Museum_Bonn_\(7267\).jpg
mv -v images/240px-Gaylussit_-_Lagunillas%2C_Venezuela.jpg images/240px-Gaylussit_-_Lagunillas,_Venezuela.jpg
mv -v images/240px-Geokronit_-_Sala%2C_Schweden.jpg images/240px-Geokronit_-_Sala,_Schweden.jpg
mv -v images/240px-Gersdorffit_-_Lobenstein%2C_Vogtland.jpg images/240px-Gersdorffit_-_Lobenstein,_Vogtland.jpg
mv -v images/240px-Gibbsite_Aluminum_hydroxide_Minas_Gerais%2C_Brazil_2998.jpg images/240px-Gibbsite_Aluminum_hydroxide_Minas_Gerais,_Brazil_2998.jpg
mv -v images/240px-Goslarita._Gostar.Hartz%2CSajonia.JPG images/240px-Goslarita._Gostar.Hartz,Sajonia.JPG
mv -v images/240px-Graftonite_with_Triphylite_Iron_manganese_calcium_phosphate_Palermo_Mine%2C_North_Groton%2C_New_Hampshire_2863.jpg images/240px-Graftonite_with_Triphylite_Iron_manganese_calcium_phosphate_Palermo_Mine,_North_Groton,_New_Hampshire_2863.jpg
mv -v images/240px-Gruenerite_Schist_Metamorphic_Rock_North_of_Keystone%2C_South_Dakota_2916.jpg images/240px-Gruenerite_Schist_Metamorphic_Rock_North_of_Keystone,_South_Dakota_2916.jpg
mv -v images/240px-Ha%C3%BCyne.jpg images/240px-Haüyne.jpg
mv -v images/240px-Harvard_Museum_of_Natural_History._Meteor_from_Coahuila_%28DerHexer%29_2012-07-20.jpg images/240px-Harvard_Museum_of_Natural_History._Meteor_from_Coahuila_\(DerHexer\)_2012-07-20.jpg
mv -v images/240px-Hauerit_-_Raddusa%2C_Sizilien.jpg images/240px-Hauerit_-_Raddusa,_Sizilien.jpg
mv -v images/240px-Hibonite_-_Esiva_eluvials%2C_Tulear_Province%2C_Madagascar.jpg images/240px-Hibonite_-_Esiva_eluvials,_Tulear_Province,_Madagascar.jpg
mv -v images/240px-Hoelite%2C_sulfur_-_Carolaschacht_Mine%2C_Freital%2C_Saxony%2C_Germany.jpg images/240px-Hoelite,_sulfur_-_Carolaschacht_Mine,_Freital,_Saxony,_Germany.jpg
mv -v images/240px-Hollandyt%2C_Polska_Sudety.JPG images/240px-Hollandyt,_Polska_Sudety.JPG
mv -v images/240px-Hydrocynkit%2C_Kopalnia_Ojuela%2C_Mapimi%2C_Durango%2C_Meksyk.jpg images/240px-Hydrocynkit,_Kopalnia_Ojuela,_Mapimi,_Durango,_Meksyk.jpg
mv -v images/240px-Ilvanite_with_quartz_and_limonite_Calcium_iron_silicate_Laxey_Mine%2C_South_Mountain%2C_Owyhee_County%2C_Idaho_3016.jpg images/240px-Ilvanite_with_quartz_and_limonite_Calcium_iron_silicate_Laxey_Mine,_South_Mountain,_Owyhee_County,_Idaho_3016.jpg
mv -v images/240px-Jakobsit_-_Jakobsberg%2C_Schweden.jpg images/240px-Jakobsit_-_Jakobsberg,_Schweden.jpg
mv -v images/240px-Jarosite_on_quartz_Potassium_iron_sulfate_Arabia_District%2C_Pershing_County%2C_Nevada_2779.jpg images/240px-Jarosite_on_quartz_Potassium_iron_sulfate_Arabia_District,_Pershing_County,_Nevada_2779.jpg
mv -v images/240px-Jeremjevite_colorless_needles_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Jeremjevite_colorless_needles_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Jordanit_-_Binnental%2C_Schweiz.jpg images/240px-Jordanit_-_Binnental,_Schweiz.jpg
mv -v images/240px-Julgoldite-%28Fe2%29-150087.jpg images/240px-Julgoldite-\(Fe2\)-150087.jpg
mv -v images/240px-Kainite_-_Grube_Brefeld%2C_Tarthun%2C_Sta%C3%9Ffurt%2C_Sachsen-Anhalt.jpg images/240px-Kainite_-_Grube_Brefeld,_Tarthun,_Staßfurt,_Sachsen-Anhalt.jpg
mv -v images/240px-Kainosite-%28Y%29-tuc1051a.jpg images/240px-Kainosite-\(Y\)-tuc1051a.jpg
mv -v images/240px-Kieseriet_%28Kieserite%29.jpg images/240px-Kieseriet_\(Kieserite\).jpg
mv -v images/240px-Kogarkoite_-_Poudrette_quarry%2C_Mont_Saint-Hilaire%2C_Quebec%2C_Canada.jpg images/240px-Kogarkoite_-_Poudrette_quarry,_Mont_Saint-Hilaire,_Quebec,_Canada.jpg
mv -v images/240px-Kryptomelan2%2C_Maroko.jpg images/240px-Kryptomelan2,_Maroko.jpg
mv -v images/240px-Lanarkite%2C_Susannite%2C_Macphersonite-359326.jpg images/240px-Lanarkite,_Susannite,_Macphersonite-359326.jpg
mv -v images/240px-Lithiophilite_with_pyrolusite_and_quartz_Lithium_manganese_phosphate_Midnight_Owl_Mine%2C_White_Picacho_District%2C_near_Wickenburg%2C_Arizona_2793.jpg images/240px-Lithiophilite_with_pyrolusite_and_quartz_Lithium_manganese_phosphate_Midnight_Owl_Mine,_White_Picacho_District,_near_Wickenburg,_Arizona_2793.jpg
mv -v images/240px-Magnesioferrite_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Magnesioferrite_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Malachite%2C_Zaire.jpg images/240px-Malachite,_Zaire.jpg
mv -v images/240px-Mari%C4%87ite_-_Rapid_Creek.jpg images/240px-Marićite_-_Rapid_Creek.jpg
mv -v images/240px-Mesolite_sample_%28Cullen_Hall_of_Minerals%29.jpg images/240px-Mesolite_sample_\(Cullen_Hall_of_Minerals\).jpg
mv -v images/240px-Miargyrite_inquartz_Silver_antimony_sulfide_flint_district%2C_idaho_2806.jpg images/240px-Miargyrite_inquartz_Silver_antimony_sulfide_flint_district,_idaho_2806.jpg
mv -v images/240px-Museo_di_mineralogia%2C_pietre_fluorescenti%2C_agrellite_3.JPG images/240px-Museo_di_mineralogia,_pietre_fluorescenti,_agrellite_3.JPG
mv -v images/240px-N%C3%A9pouite_MHNT.MIN.2005.0.63.jpg images/240px-Népouite_MHNT.MIN.2005.0.63.jpg
mv -v images/240px-Neptunite_%28USA%29.jpg images/240px-Neptunite_\(USA\).jpg
mv -v images/240px-Nosean_crystal_group_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Nosean_crystal_group_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Osumilite%2C_thick_tabulars_with_Mullite_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Osumilite,_thick_tabulars_with_Mullite_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Osumilite_tablets_with_Mullite_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Osumilite_tablets_with_Mullite_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Patr%C3%B3nite_-_Mineralogisches_Museum_Bonn.jpg images/240px-Patrónite_-_Mineralogisches_Museum_Bonn.jpg
mv -v images/240px-Pecoraite%2C_Eden_Vermont.jpg images/240px-Pecoraite,_Eden_Vermont.jpg
mv -v images/240px-Periclase_-_Ronneburg%2C_Thuringia1.jpg images/240px-Periclase_-_Ronneburg,_Thuringia1.jpg
mv -v images/240px-Perite_%28olive_green%29.jpg images/240px-Perite_\(olive_green\).jpg
mv -v images/240px-Polybasite_-_Arizpe%2C_Sonora%2C_Mexico.jpg images/240px-Polybasite_-_Arizpe,_Sonora,_Mexico.jpg
mv -v images/240px-Portlandite%2C_Ettringite_-_Mineralogisches_Museum_Bonn.jpg images/240px-Portlandite,_Ettringite_-_Mineralogisches_Museum_Bonn.jpg
mv -v images/240px-Proustite_-_Chanarcillo%2C_Copiapo_Province%2C_Atacama_Region%2C_Chile.jpg images/240px-Proustite_-_Chanarcillo,_Copiapo_Province,_Atacama_Region,_Chile.jpg
mv -v images/240px-Putoranite%2C_Talnakhite_-_Mineralogisches_Museum_Bonn3.jpg images/240px-Putoranite,_Talnakhite_-_Mineralogisches_Museum_Bonn3.jpg
mv -v images/240px-Rapidcreekite_-_Rapid_Creek%2C_Yukon.jpg images/240px-Rapidcreekite_-_Rapid_Creek,_Yukon.jpg
mv -v images/240px-Safflorite_and_Calcite3_-_Bouismas_Mine%2C_Bou_Azzer%2C_Tazenakht%2C_Ouarzazate%2C_Souss-Massa-Draa%2C_Morocco.jpg images/240px-Safflorite_and_Calcite3_-_Bouismas_Mine,_Bou_Azzer,_Tazenakht,_Ouarzazate,_Souss-Massa-Draa,_Morocco.jpg
mv -v images/240px-Samarskite-%28Y%29_-_Yancey_Co%2C_North_Carolina%2C_USA.jpg images/240px-Samarskite-\(Y\)_-_Yancey_Co,_North_Carolina,_USA.jpg
mv -v images/240px-Scheelite_MHNT.MIN.2004.0.88_%28p%29.jpg images/240px-Scheelite_MHNT.MIN.2004.0.88_\(p\).jpg
mv -v images/240px-Scol%C3%A9cite.jpg images/240px-Scolécite.jpg
mv -v images/240px-Skapolit%2C_Madagaskar%2C_Benono.JPG images/240px-Skapolit,_Madagaskar,_Benono.JPG
mv -v images/240px-Skutt%C3%A9rudite.jpg images/240px-Skuttérudite.jpg
mv -v images/240px-Spessartine_sur_quartz_fum%C3%A9.jpg images/240px-Spessartine_sur_quartz_fumé.jpg
mv -v images/240px-Stephanite_on_Calcite_-_Chanarcillo%2C_Copiapo_Province%2C_Atacama_Region%2C_Chile.jpg images/240px-Stephanite_on_Calcite_-_Chanarcillo,_Copiapo_Province,_Atacama_Region,_Chile.jpg
mv -v images/240px-Stromeyerite_%28Alice_Chodura%29.JPG images/240px-Stromeyerite_\(Alice_Chodura\).JPG
mv -v images/240px-Teallit_-_Ichocollo%2C_Bolivien.jpg images/240px-Teallit_-_Ichocollo,_Bolivien.jpg
mv -v images/240px-Tetrahedrite%2C_H%C3%BCbnerite%2C_Quartz_-_176605.jpg images/240px-Tetrahedrite,_Hübnerite,_Quartz_-_176605.jpg
mv -v images/240px-Thomasclarkite-%28Y%29-107522.jpg images/240px-Thomasclarkite-\(Y\)-107522.jpg
mv -v images/240px-Thomsenolite_and_Ralstonite_-_Ivittuut%2C_Arsuk_Firth%2C_Kitaa._West_Greenland.jpg images/240px-Thomsenolite_and_Ralstonite_-_Ivittuut,_Arsuk_Firth,_Kitaa._West_Greenland.jpg
mv -v images/240px-Titanite_crystals_on_Amphibole_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Titanite_crystals_on_Amphibole_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Traskite_%28brown%29-Kampfite_%28bluish%29.jpg images/240px-Traskite_\(brown\)-Kampfite_\(bluish\).jpg
mv -v images/240px-Tridymite_tabulars_-_Ochtendung%2C_Eifel%2C_Germany.jpg images/240px-Tridymite_tabulars_-_Ochtendung,_Eifel,_Germany.jpg
mv -v images/240px-Trona%28small%29.jpg images/240px-Trona\(small\).jpg
mv -v images/240px-Tschermigit_%28Ammonalaun%29_-_Tschermig%2C_B%C3%B6hmen.jpg images/240px-Tschermigit_\(Ammonalaun\)_-_Tschermig,_Böhmen.jpg
mv -v images/240px-Tyrolit%2C_S%C5%82owacja.jpg images/240px-Tyrolit,_Słowacja.jpg
mv -v images/240px-Ullmannit_-_Monte_Narba%2C_Sardinien.jpg images/240px-Ullmannit_-_Monte_Narba,_Sardinien.jpg
mv -v images/240px-Villiaumite1_-_Poudrette_quarry%2C_Mont_Saint-Hilaire%2C_Quebec%2C_Canada.jpg images/240px-Villiaumite1_-_Poudrette_quarry,_Mont_Saint-Hilaire,_Quebec,_Canada.jpg
mv -v images/240px-Villiaumite5_-_Poudrette_quarry%2C_Mont_Saint-Hilaire%2C_Quebec%2C_Canada.jpg images/240px-Villiaumite5_-_Poudrette_quarry,_Mont_Saint-Hilaire,_Quebec,_Canada.jpg
mv -v images/240px-Wakefieldite-%28La%29_%2C_Hausmannite_-_Grube_Gl%C3%BCcksstern%2C_Gottlob%2C_Th%C3%BCringen.jpg images/240px-Wakefieldite-\(La\)_,_Hausmannite_-_Grube_Glücksstern,_Gottlob,_Thüringen.jpg
mv -v images/240px-Walfordite_-_Tambo_Mine%2C_Elqui_Province%2C_Coquimbo_Region%2C_Chile2.jpg images/240px-Walfordite_-_Tambo_Mine,_Elqui_Province,_Coquimbo_Region,_Chile2.jpg
mv -v images/240px-Weloganite2%2811x5.5%29.jpg images/240px-Weloganite2\(11x5.5\).jpg
mv -v images/240px-Xenot%C3%ADmio1.jpeg images/240px-Xenotímio1.jpeg
mv -v images/240px-Xonotlite_Hydrous_calcium_silicate_Point_Shivery_near_Cox%27_Cove_Bay_of_Islands_Newfoundland_1928.jpg images/240px-Xonotlite_Hydrous_calcium_silicate_Point_Shivery_near_Cox\'_Cove_Bay_of_Islands_Newfoundland_1928.jpg
mv -v images/240px-Zirc%C3%A3o.jpeg images/240px-Zircão.jpeg
mv -v images/250px-Potassium_dichromate_%28synthetic%29.jpg images/250px-Potassium_dichromate_\(synthetic\).jpg
mv -v images/275px-Pi%C3%A9montite.jpg images/275px-Piémontite.jpg
mv -v images/300px-Sylvanite_%28%28Au%2CAg%292Te4%29%2C_Cripple_Creek_Diatreme.jpg images/300px-Sylvanite_\(\(Au,Ag\)2Te4\),_Cripple_Creek_Diatreme.jpg
mv -v images/lossy-page1-240px-Vaterite2-San_Vito%2C_Monte_Somma%2C_Italy.tif.jpg images/lossy-page1-240px-Vaterite2-San_Vito,_Monte_Somma,_Italy.tif.jpg
